# Generated by Django 5.1.6 on 2025-02-11 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GYMNASIO', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcion',
            old_name='cedula',
            new_name='cliente',
        ),
    ]
